### ISSUE TITLE
getting error while executing the command

### ISSUE THREAD

**Issue by cotone1807** [frohoff/ysoserial#214]
java -jar ysoserial-0.0.4.jar Spring1 'command'
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Error while generating or serializing payload
java.lang.IllegalAccessError: class ysoserial.payloads.util.Gadgets (in unnamed module @0x5a9ae579) cannot access class com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xalan.internal.xsltc.trax to unnamed module @0x5a9ae579
	at ysoserial.payloads.util.Gadgets.createTemplatesImpl(Gadgets.java:102)
	at ysoserial.payloads.Spring1.getObject(Spring1.java:57)
	at ysoserial.GeneratePayload.main(GeneratePayload.java:34)

**Comment by frohoff** [comment]
Duplicate of #176. See the thread there about `--add-opens`.
